### ISSUE TITLE
Error (global 'Locale')

### ISSUE THREAD

**Issue by Craiqq** [IngPleb/qb-trashsearch#3]
Hello i have this error 
![image](https://user-images.githubusercontent.com/106879604/172013435-e1782ac1-27c5-422d-8cd4-5908c8287cf0.png)

**Comment by IngPleb** [comment]
Have you edited the file in any way?

**Comment by Craiqq** [comment]
> 

No and i just restarted the serv it's working now i don't know how xD anyway thanks

**Comment by Craiqq** [comment]
> Have you edited the file in any way?

Now i have this problem 
![image](https://user-images.githubusercontent.com/106879604/172015485-12ab716b-09e5-46dc-a673-df6d26cf0000.png)

and i didn't edited the file

**Comment by IngPleb** [comment]
When was the last time you have updated the QBCore?
